### ISSUE TITLE
WinForms Visual Basic projects are upgraded to .NET 5 but they should be upgraded to .NET 6

### ISSUE THREAD

**Issue by adegeo** [dotnet/upgrade-assistant#1031]
For some reason the tool is choosing the `net5.0-windows` TFM. It should choose the `net6.0-windows` TFM.

**Comment by mjrousos** [comment]
How odd. Maybe a bug in the VB TFM selector. Can you confirm that this still happens after `dotnet tool update -g upgrade-assistant`?

**Comment by mjrousos** [comment]
I think I see the issue. The [VB "My" TFM selector](https://github.com/dotnet/upgrade-assistant/blob/0bfbdf260b6ebf26f48d2f1fe453914d6f8a9750/src/extensions/vb/Microsoft.DotNet.UpgradeAssistant.Extensions.VisualBasic/MyTypeTargetFrameworkSelectorFilter.cs#L42) is updating things to .NET 5 instead of using `ITargetFrameworkSelectorFilterState.AppBase`. In other words, it's got .NET 5 hard-coded instead of using the TFM that corresponds to the user's selected target (LTS, current, etc.).
