### ISSUE TITLE
https://github.com/dotnet/upgrade-assistant/issues/991#issue-1087369254

### ISSUE THREAD

**Issue by AMS-Hasz1** [dotnet/upgrade-assistant#1045]
## Summary

1-2 sentences. Say what this is about.

## Motivation and goals

1-2 paragraphs, or a bullet-pointed list. What existing pain points does this solve? What evidence shows it's valuable to solve this?

## In scope

A list of major scenarios, perhaps in priority order.

## Out of scope

Scenarios you explicitly want to exclude.

## Risks / unknowns

How might developers misinterpret/misuse this? How might implementing it restrict us from other enhancements in the future? Also list any perf/security/correctness concerns.

## Examples

Give brief examples of possible developer experiences (e.g., code they would write).

Don't be deeply concerned with how it would be implemented yet. Your examples could even be from other technology stacks.

**Comment by papyr** [comment]
This was `blindly copied and closed` without the content from the previous report/issue.

We were asking for partial support during the update.. [Convert asp MVC partials to ViewComponets or AnchorTags](https://github.com/dotnet/upgrade-assistant/issues/991#top)
#991

Context from earlier thread... since its missing here.
____________

Hello @mjrousos thanks for the suggestion.

The structure for the two are very similar so, but it sometimes pops up as an issue in the upgrade assistant.

Many of the core workers, are dynamic components with data, like widgets, portlets (cards/charts) are coded as these components.

Compared to Java and Ruby there is such little support for this, So, for the dev community, I was hoping to get an automated or GUI driven migration (with the option to supply the models). The T4 templates are quite standard, so it should be easy to port the code.

Its just that the main meat after the controllers and razor views is the ViewComponents and it would be a lot of help to have something like this for developers as .NET evolves!
