### ISSUE TITLE
Error while trying to install upgrade assistant tool

### ISSUE THREAD

**Issue by Natis88** [dotnet/upgrade-assistant#1141]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

 error NU1301: Failed to retrieve information about 'upgrade-assistant' from remote source 'https://api.nuget.org/v3-flatcontainer/upgrade-assistant/index.json'.

**Comment by sunandabalu** [comment]
@Natis88 trying to install with `--ignore-failed-sources` should resolve this.

**Comment by KohrAhr** [comment]
OS: Windows 10

Z:\>dotnet tool install -g --add-source 'https://api.nuget.org/v3/index.json' --ignore-failed-sources upgrade-assistant

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.302

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
C:\Users\XXXXXX\AppData\Local\Temp\q3o1ykii.wio\restore.csproj : warning NU1801: The local source 'Y:\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\XXXXXX\AppData\Local\Temp\q3o1ykii.wio\restore.csproj : warning NU1801: Unable to load the service index for source https://api.nuget.org/v3/index.json.
C:\Users\XXXXXX\AppData\Local\Temp\q3o1ykii.wio\restore.csproj : warning NU1801: The local source 'Y:\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\XXXXXX\AppData\Local\Temp\q3o1ykii.wio\restore.csproj : warning NU1801: The local source 'Y:\'https:\api.nuget.org\v3\index.json'' doesn't exist.
C:\Users\XXXXXX\AppData\Local\Temp\q3o1ykii.wio\restore.csproj : error NU1101: Unable to find package upgrade-assistant. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Pack
ages, nuget.org, Y:\'https:\api.nuget.org\v3\index.json'
The tool package could not be restored.
Tool 'upgrade-assistant' failed to install. This failure may have been caused by:
