### ISSUE TITLE
Please do needful -IMPORTANT

### ISSUE THREAD

**Issue by AKULASUDHIKSHANA** [dotnet/upgrade-assistant#1163]
![16551991493407363254682874526909](https://user-images.githubusercontent.com/46380106/173545464-568c52b2-0fd9-40b5-b844-f2008bc53f37.jpg)
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by ujjwalchadha** [comment]
@AKULASUDHIKSHANA  Can you try `dotnet tool install -g --ignore-failed-sources upgrade-assistant`
If you do not have api.nuget.org as a default feed, you can run `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` before running the above command.

@brandonh-msft It seems like there is a problem where the switch `--add-source 'url'` tries to add `CurrentFileDirectory + url` as the feed source instead of just `url`. @bgursahani hit the same issue

**Comment by brandonh-msft** [comment]
it seems the cmd line for `dotnet` takes the `'` character as part of the value for the source. @mjrousos could you update the doc with the right fix/value for this? Not sure if char needs to be escaped, if the char that gets c/p'd from the doc is corrupted somehow when pasted in CLI, etc.

**Comment by brandonh-msft** [comment]
I took care of it - @mjrousos or @twsouthwick if you could review & approve as Sunanda's out, that'd be great thanks
