### ISSUE TITLE
Update UA to port apps to net7 instead of net6 

### ISSUE THREAD

**Issue by OliaG** [dotnet/upgrade-assistant#1348]
We need to make sure that UA is upgrading to net7 after release of .NET7

- by default
- when --target-tfm-support is set to "Current " or "STS"

There is related task for renaming "Current " to "STS": #1347

**Comment by OliaG** [comment]
#1347

**Comment by twsouthwick** [comment]
A few things to consider while doing this that have been challenges in the past:

- Do we need to be able to load the .NET 7 SDK to enable this? Do we need to target .NET 7 to do so? I'm assuming yes (historically, that's been the case), but not sure if it's backwards compatible this release
- If we need to target .NET 7 for UA, do we want to enable people with just .NET 6 to be able to use it? If yes, we'll probably want to cross-compile a .NET 6 and a .NET 7 build. When .NET 6 came out, we did this for a while with .NET 5, but removed it at .NET 5's end of support.
- If we do cross compile, we probably want to keep .NET 6 as the current target if running on .NET 6 since we couldn't upgrade it to that.

**Comment by mjrousos** [comment]
I think it would be better to make sure the `--target-tfm-support STS` always means net7.0 and `--target-tfm-support LTS` always means net6.0, and just give an error message if users trying to use STS without .NET 7 present. Otherwise, it gets too confusing if STS means one thing for one user and something else for another.
