### ISSUE TITLE
No Instructions for net6.0-windows

### ISSUE THREAD

**Issue by aerotec-pmehner** [dotnet/upgrade-assistant#1419]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Your tool states that certain libraries do not support net7.0-windows but you don't say anything about how to run for net6.0-windows.

**Comment by engmtcdrm** [comment]
I hope I can help. I'm assuming you've installed the `.NET 6 SDK`, `Visual Studio`, and `upgrade-assistant` which are all required.

In Powershell, or whatever terminal you'd like, you can run the following commands to both analyze and upgrade a solution to .NET 6. This is assuming you installed the SDK in the default spot and you're using version `6.0.406`.

## Analyze

`--msbuild-path` - Points to the SDK location on your computer the double back slash `\\` at the end **IS REQUIRED**
`-t LTS` - Makes sure it is .NET 6 because that is the current long term release
`--format html` - Outputs the analysis as a `.html` file, remove to output as `.sarif`.

```sh
upgrade-assistant analyze --msbuild-path 'C:\\Program Files\\dotnet\\sdk\\6.0.406\\' --format html <Path to csproj or sln to analyze>
```

## Upgrade

`--msbuild-path` - Points to the SDK location on your computer the double back slash `\\` at the end **IS REQUIRED**
`-t LTS` - Makes sure it is .NET 6 because that is the current long term release
`--non-interactive` - Skips prompts during upgrading. I would probably remove this the first time and step through the upgrade the first time making sure things are upgrading as to be expected.

```sh
upgrade-assistant upgrade --msbuild-path 'C:\\Program Files\\dotnet\\sdk\\6.0.406\\' -t LTS --non-interactive <Path to csproj or sln to analyze>
```

**Comment by mgoertz-msft** [comment]
No longer applicable.
