### ISSUE TITLE
Mac - non-interactive throws an error immediately

### ISSUE THREAD

**Issue by davidortinau** [dotnet/upgrade-assistant#1459]
Running the preview build on macOS, I was unable to use the recommend --non-interactive mode.

<img width="1522" alt="MicrosoftTeams-image (21)" src="https://user-images.githubusercontent.com/41873/228892521-b5ed3c9f-3641-4eff-b6ed-e928b2730483.png">

I was able to run this by removing that option.

Project I ran against: https://learn.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/deeplinking/

**Comment by jstedfast** [comment]
I think the issue here is that on macOS, the `*` in the command-line is being expanded by the shell (zsh?) to be all of the file/directory names in the current working directory (which is what explains the error about README.md, iOS, Screenshots, etc).

@mgoertz-msft suggests maybe we should default to upgrading *all* projects if a --entry-point isn't specified to make it redundant (to avoid this scenario altogether).

The code may already do this, but we can check and if it doesn't, make it work.

**Comment by mgoertz-msft** [comment]
No longer applicable.
