### ISSUE TITLE
Error: Unknown command 'analyze'.

### ISSUE THREAD

**Issue by molakavenugopal** [dotnet/upgrade-assistant#1491]
Problem encountered on https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by manojgudi2016** [comment]
Same here, I used analyze command before on a different machine but I had a new machine that just has VS2022 installed with  7, 5, 3.1, 3.0 and 2.1 SDKs on my new machine.

What could be the possible case why the latest installed Upgrade-Assistant is unable to identify the analyze command?

![image](https://github.com/dotnet/upgrade-assistant/assets/17130151/bb612f56-8c52-4012-afa6-4a88f2883040)

**Comment by naresh3132** [comment]
@tugberksahinoglu how to install previous version of it ?

**Comment by manojgudi2016** [comment]
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.
To-Uninstall existing latest version from the system:
C:\Users\USER1>dotnet tool uninstall --global upgrade-assistant
Tool 'upgrade-assistant' (version '0.5.30') was successfully uninstalled.

To Install previous version.
C:\Users\USER1>dotnet tool install --global upgrade-assistant --version 0.4.421302
You can invoke the tool using the following command: upgrade-assistant
Tool 'upgrade-assistant' (version '0.4.421302') was successfully installed.

After this I can use the analyze command.

However if the team has developed a new version and remove the analyze command, there might be a purpose behind it. 
I personally like the analyze command as it provides an interactive way and provides a view of the packages that needs changes.

**Comment by eduarddejong** [comment]
I wanted to use this tool right know and I noticed the same. It's not even metioned in the `--help` anymore.

If it's a removed feature, it would be nice if the application at least explains that in the error message.

So let's asume it's bug.

**Comment by Behodar** [comment]
Same issue here. I was using a previous version (not sure of the number) and the command worked, but it disappeared after doing a "dotnet tool update -g upgrade-assistant".

**Comment by Behodar** [comment]
https://dotnet.microsoft.com/en-us/platform/upgrade-assistant/tutorial/install-upgrade-assistant makes no mention of legacy. It sounds like this is a case of the documentation needing to be updated.

**Comment by eduarddejong** [comment]
> Microsoft has mentioned it in their documentation [here](https://learn.microsoft.com/en-us/dotnet/core/porting/upgrade-assistant-install-legacy) you need to install legacy version to get the Analyze feature, as it is not yet delivered in the latest version.

Ok, so it says:
"Starting with version 0.5.2, the code base for the .NET Upgrade Assistant CLI tool was **rebased** on the Visual Studio extension. This means that there are effectively two different CLI tools, the version prior to 0.5.2 which is referred to as the legacy version, and the 0.5.2+ version which is the current version.
The legacy version has some functionality that is not **yet** available in the new version such as analyze command or solution-level upgrades, but also lacks new improvements available in the new (0.5.2+) version. Therefore, you may want to use it until the current version increases in capability and scope."


Ok, So this basically means the situation is kind of a temporary situation.
The thing is that this application is still in a 0.* versioning phase. So it's practially all still very much Beta and anything can change at any moment.
I understand it.


However, it would be greater if they at least mentioned something on Github the README here, since that's the first place where I am looking for information. Just like many other open source projects do.
I didn't even know that whole documentation link.
I know this tool from a .NET Conf video and installed it for that reason.
