### ISSUE TITLE
Give better error messages concerning VB .NET projects

### ISSUE THREAD

**Issue by bigtfromaz** [dotnet/upgrade-assistant#265]
This is a question, not a bug report although it may be a docup.

We are evaluating options for porting a solution having 20 projects; 11 C# and 9 VB.  Project types include command line, class libraries, ASP.NET, Windows Forms with dataset bindings, and OleDB.

I picked a VB project having no dependencies other than .NET, and ran this command: 
`upgrade-assistant MyVBapp.vbproj` 

This is what I received:
`Unhandled exception: System.InvalidOperationException: Cannot open project 'D:\Temp\afolder\MyVBapp.vbproj' because the language 'Visual Basic' is not supported.`

Perhaps this exception should be handled and a message issued, rather than dumping the stack trace.  In addition, when running the command against the solution, the tool is silently skipping VB projects in Step 1.  It would be helpful to see warnings when that occurs.

Obviously the version I am running does not support VB.   Here are the releases:
```
try-convert            0.7.212201      try-convert
upgrade-assistant      0.2.212505      upgrade-assistant
```

There are two possibilities.  I am:

  1. running the an old version where VB is not supported

  2. or...running the latest preview version and VB is still not supported.  

In any event, it would be good to find this restriction in the documentation.  Perhaps I missed it.

Should we wait for the tooling to mature?  We're willing to proceed. However we are hoping this tool will reduce our LOE and increase the chances the project will get funded.

**Comment by mjrousos** [comment]
Thanks for the report @bigtfromaz. As you've discovered, we don't have support for VB yet. It's on our roadmap, but the tool is just in its early stages and I'm afraid it only supports C# projects, so far.

You're right, though, that the error message can be better in the case where a user runs the tool on a vbproj. Lets use this issue to track making that messaging better and I'll open a separate issue to track implementing support for VB projects.

**Comment by twsouthwick** [comment]
Let's see if we can get a VB integration project (maybe just a console app right now), and ensure everything but code analyzers will work. Probably just need to bring in the roslyn VB support for that via Microsoft.CodeAnalysis

**Comment by mjrousos** [comment]
Sounds good.

**Comment by KSchlobohm** [comment]
Thanks for the report @bigtfromaz. We've modified the approach to start our journey toward supporting Visual Basic .NET projects.

Please note that this is still the beginning of our journey and we're continuing to evolve the upgrade process. While the recent PR adds support to process VB project files (console apps, win forms apps, and class libraries) we found some limitations with `try-convert` that prevent us from helping with VIsual Basic WPF projects.

Here's a link to the related issue so that you may track that if it impacts your scenario.
[#384 Add support for Visual Basic WPF projects](https://github.com/dotnet/try-convert/issues/384)

And, a link to another issue we opened to enhance the support for Visual Basic ASP.NET apps
#310

Thanks for your feedback!
