### ISSUE TITLE
I am stuck here unable to select next project

### ISSUE THREAD

**Issue by woaksie** [dotnet/upgrade-assistant#284]
[13:58:49 INF] Initializing upgrade step Select project to upgrade

Upgrade Steps

Entrypoint: D:\Projects\Neural-Network\NeuralNetwork\NeuralNetwork\NeuralNetwork.csproj

1. [Next step] Select project to upgrade
2. Finalize Solution

Choose a command:
   1. Apply next step (Select project to upgrade)
   2. Skip next step (Select project to upgrade)
   3. See more step details
   4. Configure logging
   5. Exit
> 1
[13:59:06 INF] Applying upgrade step Select project to upgrade
Here is the recommended order to upgrade. Select enter to follow this list, or input the project you want to start with.
   [Completed] NeuralNetwork
>
[13:59:35 ERR] Unknown selection: ''
> 4
[13:59:48 ERR] Unknown selection: '4'
>
[14:00:08 ERR] Unknown selection: ''
> 1
[14:00:13 ERR] Unknown selection: '1'
> quit
[14:00:21 ERR] Unknown selection: 'quit'
> 2
[14:00:31 ERR] Unknown selection: '2'
>
[14:00:37 ERR] Unknown selection: ''
> NeuralNetwork
[14:00:58 ERR] Unknown selection: 'NeuralNetwork'
>
[14:01:05 ERR] Unknown selection: ''
>
[14:01:21 ERR] Unknown selection: ''
> 2
[14:01:59 ERR] Unknown selection: '2'
> 1
[14:02:01 ERR] Unknown selection: '1'
> 2
[14:02:03 ERR] Unknown selection: '2'
> 3
[14:02:04 ERR] Unknown selection: '3'
> 4
[14:02:05 ERR] Unknown selection: '4'
> 5
[14:02:07 ERR] Unknown selection: '5'
>

**Comment by mjrousos** [comment]
Thanks for the report, @woaksie. Are you able to share the solution so that I can try to reproduce the issue?

Alternatively, if you run the tool with "-v" that will produce much more verbose output and if you share that output, it may give some hints as to what's going on here.

**Comment by woaksie** [comment]
There are 3 projects in the solution and I had just done the first one. I was expecting to see the other 2 projects when I selected the option "1 Apply next step (Select project to upgrade)" but it only showed me the completed project. and I could not enter any option that would get past this. I actually don't care about the other two projects at this point and would just like to "Finalize Solution".  What would happen if I terminate the upgrade and start it again? I am happy to share the solution although it is a bit of an experimental mess [don't judge me ;-)]. Should I zip up the backed up solution?

**Comment by mjrousos** [comment]
@woaksie, if you don't care about upgrading the other two projects, then just terminating the upgrade assistant is fine. The only thing 'finalize solution' does is update some internal state the tool uses.

Since the backup is too large, can you maybe zip up just the project files instead? Even without source, I can probably use the project files to re-create the issue and look into what went wrong.

**Comment by woaksie** [comment]
I managed to get it down in size by deleting the bin contents and a resharper file.
[NeuralNetwork.backup.zip](https://github.com/dotnet/upgrade-assistant/files/6065248/NeuralNetwork.backup.zip)

**Comment by mwilsonray** [comment]
I'm having the same issue with a solution that contains 9 projects. Started the assistant with the solution and it asked to select an entry point (one of the projects) and I was able to upgrade that project. After that, the assistant only shows the project I upgraded and none of the others. I can specify the individual .xxproj files, but I was hoping it would show the order and guide me thru. I cannot upload the project, but here is the cleansed .sln structure:

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Main.UI", "Main.UI\Main.UI.csproj", "{67D5E049-38D6-45C1-AD30-7A58D1F12BC2}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Main.API", "Main.API\Main.API.csproj", "{4E2B834B-21B5-4ED6-B387-090AF9DF152A}"
EndProject
Project("{00D1A9C2-B5F0-4AF3-8072-F6C62B433612}") = "Main.Database", "Main.Database\Main.Database.sqlproj", "{FAECC36D-EA68-4023-A221-31DED5A5CE7F}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "SubApp", "SubApp", "{4EA62A0D-C2AD-4F54-8AAA-30D46AED866D}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SubApp.Api", "SubApp\SubApp.Api\SubApp.Api.csproj", "{4E8E187D-447A-49CD-BF85-F5E0D9B2C03C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SubApp.BusinessLogic", "SubApp\SubApp.BusinessLogic\SubApp.BusinessLogic.csproj", "{6E108F29-13D4-452F-BF4E-B1297E4E2863}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SubApp.DataAccess", "SubApp\SubApp.DataAccess\SubApp.DataAccess.csproj", "{0E9CC38E-BAE3-4396-8BB8-7B7180421A8B}"
EndProject
Project("{00D1A9C2-B5F0-4AF3-8072-F6C62B433612}") = "SubApp.Database", "SubApp\SubApp.Database\SubApp.Database.sqlproj", "{48938BE2-77AE-4E3D-9D22-1190943176D6}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SubApp.Tests", "SubApp\SubApp.Tests\SubApp.Tests.csproj", "{BB8F0767-6E1D-4992-8F3E-AC4EAE7873F0}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Main.Scheduler", "Main.Scheduler\Main.Scheduler.csproj", "{70A17922-D031-43BA-BE4C-79A099D70A93}"
EndProject

**Comment by mjrousos** [comment]
@woaksie, I took a look at the project you uploaded, but it seems to only be one project (which the tool runs fine on). Are you able to share the solution with multiple projects so that I can try to reproduce the issue of the tool failing after completing the first upgrade? Even having just the csproj files without source might be good enough to reproduce the issue.

Also, @woaksie  and @mwilsonray, if you can run the tool with the -v parameter and share the output that may give some clues.

**Comment by mwilsonray** [comment]
Company.CommonUI is an internal NuGet pkg that is source code only (cs, js, css, etc.) and none of the csproj files have Code Analylzer references. Unfortunately, I cannot send the csproj or sln files.

[upgrade-assistant-01.log](https://github.com/dotnet/upgrade-assistant/files/6071682/upgrade-assistant-01.log)

**Comment by mjrousos** [comment]
Thanks, @mwilsonray. I'll take a look.

**Comment by woaksie** [comment]
Sorry about that, that was the backup the tool made. I thought it did the whole solution but it just did the project. I have deleted the solution and recreated it from Git. These are the 3 project files
[NeuralNet.zip](https://github.com/dotnet/upgrade-assistant/files/6072020/NeuralNet.zip)

**Comment by nzain** [comment]
I have the same problem after successfully upgrading 4/11 projects (the other 7 were compliant already). All were marked green "completed". It seems the tool does not detect that all projects have been completed but suggests "move to next project" anyways. Then there is nothing to select and it runs into the described deadlock situation. Unfortunately, I can't share the solution.

I could imagine that the tool gets confused because my directory contains even more, unrelated projects (plugins that would be built independently). Those are neither linked in the sln nor referenced by the 11 csproj files the tool should look at. The command line "user" interface correctly identified the dependency structure and showed only relevant projects.

**Comment by mjrousos** [comment]
Thanks for sharing the repro, @woaksie. I think I see the issue and am working on a fix now.
