### ISSUE TITLE
GenerateManifests=true property should be handled

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/upgrade-assistant#394]
If a project (such as BabySmash) has the property `GenerateManifests=true`, it cannot be built from .NET Cli. This property is associated with ClickOnce but doesn't seem to be fully supported. We have a few options:

- Remove this property if found in projects
- Warn users that it is there and that they won't be able to build from CLI
- Identify if there is a product gap here and it should be supported

**Comment by twsouthwick** [comment]
Checking to see if this is something msbuild could support: https://github.com/dotnet/msbuild/issues/6313

**Comment by shanselman** [comment]
Adding context:

When converting BabySmash, the resulting WPF app works, but:
* Can't be built from "dotnet build" - can only be built within VS/with msbuild.
* The property GenerateManifests being set to true chain triggers down to a call to MSBuild for a task FormatUrl (https://docs.microsoft.com/en-us/visualstudio/msbuild/formaturl-task?view=vs-2019) which is fairly intuitively named; It formats a URL. The .NET CLI version of MSBuild does not support this task and thus rejects the build.
WPF projects trigger a build task called MarkupCompilePass1 (https://docs.microsoft.com/en-us/visualstudio/msbuild/markupcompilepass1-task?view=vs-2019) to process the xaml/cs views files into generated .g.cs and baml files. If the build failed due to the GenerateManifests error then that dotnet.exe process would hang and subsequent builds will fail due to a collision on the WPF .g.cs generated files. 
* Ideally WPF/WinForms apps that have been converted CAN be built with 'dotnet build' at the CLI
* Fixing this allowed me to be able to use a GitHub Action to build BabySmash for free on GitHub.
* Should/can the try-convert tool be updated to handle this case so as to unblock customers both at the CLI and in GitHub Actions/DevOps?

**Comment by paulomorgado** [comment]
@shanselman, can it be built with `dotnet msbuild`?

**Comment by carterlist** [comment]
Does this mean it's currently impossible to build a WPF application with ClickOnce in Azure? What is the timeline for resolving this issue?
