### ISSUE TITLE
Query : Analyzers & CodeFixes added to the solution

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [dotnet/upgrade-assistant#443]
Hi,
The Readme section mentions that "Analyzers added to the solution will highlight some of the remaining changes needed after the tool runs."

I see a Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CSharp.Analyzers and Microsoft.DotNet.UpgradeAssistant.Extensions.Default.CSharp.CodeFixes added to my solution post conversion using the tool.

How do I make use of these to understand the further changes required?

**Comment by mjrousos** [comment]
These analyzer packages will cause the recommended source code changes the tool makes to show up as warnings in the IDE. There's no special action you need to take - just open the project in VS. At the moment, though, there are only a handful of analyzers and they all have associated code fix providers so the necessary changes should have already been made by running the tool.

So, in the tool's current state, you're not likely to see any extra diagnostics (unless code changes to re-introduce an issue) since the tool is able to fix all of the diagnostics it can find at the moment. As Upgrade Assistant matures, more analyzers will be introduced, including some that the tool won't be able to fix but will give warnings on. These docs are mostly looking forward to that future state.
