### ISSUE TITLE
Do not insert WebTypeReplacements.typemap file into my project

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#631]
### Describe the bug
After an upgrade, I was not expecting to see a `WebTypeReplacements.typemap` file in my class library project.

### To Reproduce
1. Make a new class library project
2. Run upgrade assistant on a class library project

![image](https://user-images.githubusercontent.com/23503973/122117115-18fad600-cdec-11eb-8347-1d8c5c13b799.png)

### Exceptions (if any)
None

### Further technical details
- Windows version:__10__ and bitness: __64-bit__
- Include the output of `dotnet --list-sdks`

3.1.410 [C:\Program Files\dotnet\sdk]
5.0.203 [C:\Program Files\dotnet\sdk]
5.0.204 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
5.0.300 [C:\Program Files\dotnet\sdk]
5.0.301 [C:\Program Files\dotnet\sdk]
6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

- Include the output of `upgrade-assistant --version`
> current version

**Comment by mjrousos** [comment]
Good catch, @KSchlobohm. On the one hand, I like having the typemap file come along with our analyzers so that it's easy to find and customize but you're definitely right it doesn't belong in the project root. I can think of two possible fixes here:

1. Move this file under Properties/My Project so that it's more subtle but still available.
2. Package this as an embedded resource in the analyzer project (users could still add their own typemaps). This has the advantage of not adding any extra files at all to the project but would mean that customers are unlikely to discover that they can customize type upgrades via config.

@dotnet/dotnet-upgrade-assistant-team, any opinions on what the best design here would be?

**Comment by KSchlobohm** [comment]
option1 seems the most flexible to me.  as an end user I would want to retain the ability to edit this map as well as add to the list.

**Comment by mjrousos** [comment]
Sounds good. PR incoming...
