### ISSUE TITLE
Inform users about NuGet packages that should be replaced

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#725]
## Summary
`upgrade-assistant` will help find the newest version of a package but there are other upgrade scenarios where the latest version is not the recommended approach. Instead, we want to inform that there is a newer package that should be considered.

## Motivation and goals
If someone has a reference to [RhinoMocks](https://www.nuget.org/packages/RhinoMocks/) then recommending an upgraded package version does not help to address the problem. If someone has a reference to [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) then we want to recommend a package that has not been deprecated.

## In scope

1. [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/)
2. [Microsoft.IdentityModel.Clients.ActiveDirectory](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/)

## Out of scope
It looks like the NuGet feed has access to an attribute that describes that the package is deprecated. It does not always have a link to a recommended replacement package.

## Risks / unknowns

*How might developers misinterpret/misuse this?*
- Should be careful that when we recommend a replacement that it is actually a recommendation. Many find that Moq is an easy replacement for RhinoMocks but there may be alternatives I haven't considered.

*Also list any perf/security/correctness concerns.*
- There's a risk that upgrade-assistant would recommend the wrong package. one of the recommendations could become deprecated. This risk is somewhat deflated by the knowledge that the recommendation should always be newer, and an improvement over, the package that was detected.

## Updates 7-28-21

As per Risks, `upgrade-assistant` should not be the owner of data that describes which package **is** or **is not** deprecated. `upgrade-assistant` also should not own the details about which package should be recommended as an upgrade. This data should come from the NuGet API.

Example: 

The [Windows.Azure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/) package is a deprecated package with a recommended replacement.

The API to describe this deprecation is available at: https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#package-deprecation

And the details for this package appear as:
![Deprecated package](https://user-images.githubusercontent.com/23503973/127392650-da2a871c-079d-4cb0-9bcc-34fca52c0318.png)

**Comment by twsouthwick** [comment]
I can see the value of this, but most of these will not be a 1:1 replacement. If we were to do this, we would want each dependency change to be something people opt into (instead of applying for all)

**Comment by KSchlobohm** [comment]
One approach could involve a key value pair file to suggest packages that should be replaced with a value that explains why. This would enable users to override the recommended setting with their own preference.

Possibly extend the scenario to recommend a newer package. If a package replacement is recommended then we could automate the process.

**Comment by mjrousos** [comment]
If APIs mostly map 1:1 form the old package to the new one, then we can do this with package maps. I agree with Taylor, though, that if switching packages will also involve a lot of API updates, we might want to just detect package usage and let users know what they need to do.

**Comment by Sweekriti91** [comment]
This is a scenario where this applies for Xamarin-MAUI Conversion. For public and community packages, the requirement check is a blanket check, if the nuget takes a dependency on Xamarin.Forms package, then either of the two options can happen :
 1. there is an updated version of the package with updated MAUI dependencies -> we update the package
 2. there is no updated version of the package => throw warning to user that this package needs updating (or as mentioned in the proposal, if the package author has a recommended package, show that option, or basically provide them with a list of these packages that need updating, and user has to manually manage them after UA process is completed)
 
 For this public and community package check, instead of maintaining a manually created list since we don't have a list of *bad* or *known bad* packages or for that matter even a list of what they should be updated to, I was wondering if there's some way to combine doing an API call to nuget.org and then cross referencing if the nuget definition has a dependency for XF and then showing the appropriate warning.
