### ISSUE TITLE
Set class libraries for web apps to multi-target .net framework and .net standard

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/upgrade-assistant#865]
## Summary

When the **entrypoint** is an ASP.NET web app the tool should handle class library projects differently. Instead of trying to transition to `netstandard2.0` the class library should be multi-targeted to `netstandard2.0` and to target a .Net framework version compatible with the web app.

## Motivation and goals

Currently the tool will convert class libraries to `netstandard2.0` as the default. This works for many scenarios but creates challenges for ASP.NET framework web apps that do not support *PackageReference* restore style. The two challenges are:

1. Transitive dependencies are not copied to the `\bin` directory which causes runtime errors
2. The full scope of dependencies is not made available to MSBUILD. This means Visual Studio cannot display warnings about *BindingRedirects* which are required for ASP.NET framework web apps when different dependency versions are required. Failing to add the the *BindingRedirects* also causes a runtime error in the ASP.NET framework web app.

Using multi-targeting to build a .net version of a class library retains the behavior of copying transitive dependencies to the `\bin` directory for class libraries that use the new SDK style `.csproj` format and *PackageReference* restore. Because the dependencies are copied to the `\bin` directory MSBUILD can also make *BindingRedirect* warnings.

Using multi-targeting to build the netstandard version of a class library retains the behavior desired going forward with the upgrade.

## In scope

1. Changing the TargetFrameworkSelector so that it can understanding this scenario
2. Reviewing the way NuGet package minimum versions are evaluated to make best guess for compatibility when packages are upgraded

## Out of scope

1. Modifying the csproj of the ASP.NET framework web app.
2. In some scenarios a compatible NuGet package may not be available for .NET Framework. Display the "no compatible packages" message we already use when necessary.
3. For class libraries with web dependencies: Creating an interface, and/or using preprocessor directives to make code conditional for .net framework or .net standard is out of scope.

## Risks / unknowns

1. Class libraries with web dependencies may still encounter runtime errors after upgrade. 
2. Switching a class library to multi-targeting is a temporary step. This is only recommended while the web solution is using the [Strangler Pattern](https://docs.microsoft.com/en-us/dotnet/architecture/porting-existing-aspnet-apps/strategies-migrating-in-production#apply-the-strangler-pattern) and deploying 2 web projects side-by-side. Once all features are fully migrated to ASP.NET core the multi-targeting should be removed. A comment in the csproj can help users understand this recommendation.
3. The compiler will have to build the same project twice which can lead to slower overall build time

**Comment by mjrousos** [comment]
One challenge here will be code fixers. If a code fix provider (used by the source updater step) would replace a .NET Framework-only API with a .NET Core or .NET Standard-only one, what does it do with multi-targeted projects? At the moment I think the only code fixers like that are for web scenarios and hopefully there aren't too many libraries with System.Web dependencies. But in cases where they are, we will need to think about what the code fixes should do.

The other challenges that come to mind, you already list - we'll need to update the NuGet package version update step so that it chooses versions that work with all targeted TFMs and we'll need to update the target framework selector so that it correctly handles projects with multi-targeted dependent projects.
