### ISSUE TITLE
Type 'System.Windows.Threading.Dispatcher' is not defined after upgrade

### ISSUE THREAD

**Issue by attiqeurrehman** [dotnet/upgrade-assistant#935]
- [x ] Include the log file `upgrade-assistant.clef` that is produced in the working directory
- [x ] Include the analysis report `AnalysisReport.sarif ` that is produced

### Describe the bug

During analyze phase there were no indication of of this error but after upgrade the error:

> Type 'System.Windows.Threading.Dispatcher' is not defined

Enabling the property `UseWPF `to `true `seems to fix this issue:

`<UseWPF>true</UseWPF>`

But it's not a WPF and ideally I don't want to keep this property. 

### Further technical details
- Windows 10 64 bit 
- List of sdks:
   3.1.415 [C:\Program Files\dotnet\sdk]
   5.0.402 [C:\Program Files\dotnet\sdk]
   5.0.403 [C:\Program Files\dotnet\sdk]
   6.0.100 [C:\Program Files\dotnet\sdk]
- Upgrade assistant: 0.3.255803+d72527aefab54bfbadc3227b4f1ffd326c1e9a8a

[upgrade-assistant.zip](https://github.com/dotnet/upgrade-assistant/files/7533810/upgrade-assistant.zip)

**Comment by twsouthwick** [comment]
We should be adding the `UseWPF` because that API is in WindowsBase, which is available through WPF. We should verify the project component selector is detecting that.

> But it's not a WPF and ideally I don't want to keep this property.

This API is a WPF related API so you will need the `UseWPF` tag. If you don't want to use that, you'll need to find a different dispatcher that works for your scenario.

**Comment by attiqeurrehman** [comment]
thanks for clarification.
