### ISSUE TITLE
Cannot target DOTNET 5.0 for upgrade

### ISSUE THREAD

**Issue by Loophole62ndFF** [dotnet/upgrade-assistant#969]
There appears to be no way to tell the Upgrade Assistant to target DOTNET 5.0 instead of 6.0.  Nor do there seem to be any DOTNET-Target-Specific releases of Upgrade Assistant to roll back to.

**Comment by lunchin** [comment]
This worked me in command line before running tool
`set DefaultTargetFrameworks__LTS=net5.0`

then using running with this option 
`--target-tfm-support LTS`

**Comment by Loophole62ndFF** [comment]
Thank you for that suggestion - I will try it and see if it works for me as well.  How on earth did you discover that, though?

**Comment by lunchin** [comment]
Open source is the best :)

https://github.com/dotnet/upgrade-assistant/blob/main/src/cli/Microsoft.DotNet.UpgradeAssistant.Cli/appsettings.json

**Comment by Loophole62ndFF** [comment]
Hmm.  Didn't work for me - at least, not as expected.  I used the command as shown above, and tested it on one csproj file (comparing it to a csproj from a newer application that has been built against DOTNET 5.0).

The upgrade assistant created a csproj with: `<TargetFramework>netstandard2.0</TargetFramework>` rather than the expected `<TargetFramework>net5.0</TargetFramework>`?

**Comment by lunchin** [comment]
I think there is logic in the tool that will target netstandard2.0 if it can if it is a library project.

[source
](https://github.com/dotnet/upgrade-assistant/blob/main/src/components/Microsoft.DotNet.UpgradeAssistant/TargetFramework/TargetFrameworkSelector.cs)

**Comment by sunandabalu** [comment]
Yes, that is correct there is no straight-forward way to upgrade to .NET 5.0 using upgrade-assistant since we switched LTS, Current and Preview to be .NET 6.0. Also, .NET 5.0 is EOL in a few months, so its probably a good idea to move to .NET 6.0 which is a LTS release meaning its going to be around for 3 years. Closing this issue as there is nothing actionable UA team can do here, feel free to continue discussions if need be.
