### ISSUE TITLE
No way to select upgrade options when upgrading in cmd line

### ISSUE THREAD

**Issue by papyr** [dotnet/upgrade-assistant#990]
Hello, after i run the upgrade tool, the tool lists multiple targets but `no way to select which one to target` on the command line after running tool

**Comment by sunandabalu** [comment]
@papyr could you share a screenshot of what you are seeing? And also the `upgrade-assistant.clef` file if possible.

**Comment by papyr** [comment]
There are several issues, I have moved on from that, since I dint hear back for a month. 

In summary, when I upgrade a solution, it shows what targets are available in my machine, but `upgrade-assitant` **wont let me select anyone.**

https://stackoverflow.com/questions/70474916/upgrading-from-net-framework-4-7-2-to-net-6-using-upgrade-assistant-upgrades-to

**Comment by sunandabalu** [comment]
@papyr The only supported values for `tfm-support` are Current, LTS or Preview, it will not take specific TFM value or any other value. Also I see that you mentioned, that your library got converted to .netstandard 2.0 instead of 6.0, this is expected behavior in upgrade-assistant. There is logic added to determine the type of project to determine the TFM to move to, for a library project it will move to netstandard whereas an exe will move to .net6.0.

**Comment by papyr** [comment]
Even the current tfm or the the LTS dont resolve correctly
